### ISSUE TITLE
feat: Implement Toolbar component

### ISSUE THREAD

**Issue by rosielsh** [rosielsh/marka-editor#24]
## Task Description
- A clear and concise description of what the task is.

## Objectives

- [x] Objective 1: The Toolbar may be wrapped in a Toolbar Group, or it may be independently inside the Toolbar as a Toolbar Item rather than a Toolbar group.
- [x] Objective 2: Think and implement basic styling on how to set provider.
- [x] Objective 3: Write each storybook.

## Time Estimate

- Estimated Duration: 2 days
