### ISSUE TITLE
feat: Deploy Storybook

### ISSUE THREAD

**Issue by rosielsh** [rosielsh/marka-editor#29]
## Task Description
Set up and deploy Storybook instance to a publicly accessible URL, to easily view and interact with our component library.

## Objectives

- [x] Objective 1: Set up a build script for Storybook in project.
- [x] Objective 2: Choose and configure a hosting platform.
- [x] Objective 3: Create and configure a CI/CD pipeline for automatic Storybook deployment on main branch updates.
- [x] Objective 4: Deploy the initial version of our Storybook to the chosen platform.

## Technical Details
Refer to Storybook deployment documentation: https://storybook.js.org/docs/react/sharing/publish-storybook

## Notes

- Ensure all environment variables are properly set in the CI/CD pipeline.
- Consider setting up a custom domain for the Storybook instance if required.
- Make sure to exclude any sensitive information or internal components from the public Storybook if necessary.
