### ISSUE TITLE
chore: Detach the storagebook folder from monorepo packages

### ISSUE THREAD

**Issue by rosielsh** [rosielsh/marka-editor#35]
## Task Description
- A clear and concise description of what the task is.

## Objectives

- [ ] Objective 1: Describe the specific action to be done.
- [ ] Objective 2: Describe the next action if applicable.
- [ ] Objective 3: Additional task details.

## Technical Details

```code_snippet_here```

## Dependencies

- Depends on task #123
- Blocks task #456

## Time Estimate

- Estimated Duration: X hours/days
